sonar.verbose=true
sonar.organization=anshul9527
sonar.projectKey=anshul9527-mykey_anshul9527
sonar.projectName=anshul9527
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

